# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:

    - step:
        name: 'Build ppu_top.v'
        deployment: staging
        script:
          - echo "Changing to new non-root user"
          - useradd -rm -d /home/builder -s /bin/bash -g root -G sudo -u 1001 builder
          - apt update
          - apt install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git unzip iverilog gtkwave yosys
          - wget https://github.com/chipsalliance/verible/releases/download/v0.0-2130-gb11bba24/verible-v0.0-2130-gb11bba24-Ubuntu-18.04-bionic-x86_64.tar.gz
          - tar -xf verible-v0.0-2130-gb11bba24-Ubuntu-18.04-bionic-x86_64.tar.gz
          - sudo cp verible-v0.0-2130-gb11bba24/bin/verible-verilog-format /usr/local/bin/
          - wget https://github.com/MikePopoloski/slang/releases/download/v0.9/slang-linux.tar.gz
          - tar -xf slang-linux.tar.gz
          - sudo cp slang/bin/slang /usr/local/bin/          
          - su builder
          - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
          - echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
          - echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
          - echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n eval "$(pyenv init --path)"\nfi' >> ~/.bashrc
          - source ~/.bashrc
          - pyenv install 3.10.0
          - pyenv global 3.10.0
          - pip install maturin
          - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          - source $HOME/.cargo/env
          - git clone git@bitbucket.org:riscv-ppu/hardposit.git
          - cd hardposit/bindings/py-hardposit
          - make
          - cd $HOME
          - mkdir RISCV-PPU && cd RISCV-PPU
          - git clone git@bitbucket.org:riscv-ppu/ppu.git
          - git clone git@bitbucket.org:riscv-ppu/pacogen.git PACoGen
          - cd ppu
          - source .env
          - git checkout pipeline
          - make gen-test-vectors
          - make ppu WORD=64 F=32 N=8 ES=0
          - ls fpga/quartus/

          
          

          





 

          

    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - echo "Your deployment to production script goes here..."
