[package]
name = "fastop"
version = "0.1.0"
authors = ["Francesco Urbani <francescourbanidue@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
softposit = "0.3.9"
plotlib = "0.5.1"
num-traits = "0.2.14"
