# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the pipeline branch
  push:
    branches: [ disabled ]
  pull_request:
    branches: [ disabled ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ns: [8,16]
        word: [32,64]
        es: [0,1,2]
    container: federicorossir/ppuvhdl-env:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          export RISCV_PPU_DIR=$(cd .. && pwd)
          make gen-test-vectors
          make ppu WORD=${{ matrix.word }} F=32 N=${{ matrix.ns }} ES=${{ matrix.es }}
        
          
      - name: Upload ppu top
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: ppu_top
          path: fpga/vivado/*.v

  report:
    runs-on: ubuntu-latest
    container: siliconbootcamp/xilinx-vivado:stable
    needs: build
    
    steps:
      - name: Run a multi-line script
        run: |
          /tools/Xilinx/Vivado/2021.1/bin/vivado -mode batch -nojournal
          

